/* Generated by tools/build-decks.mjs — do not edit by hand. */
const DECKS_INDEX = {
  "group": {
    "ru": {
      "pages": 19,
      "title": "UNB Group — платформа мониторинга инфраструктуры"
    },
    "en": {
      "pages": 19,
      "title": "UNB Group — infrastructure monitoring platform"
    },
    "uz": {
      "pages": 19,
      "title": "UNB Group — infratuzilma monitoringi platformasi"
    }
  },
  "solar": {
    "ru": {
      "pages": 15,
      "title": "Солнечные станции — AI-инспекция"
    },
    "en": {
      "pages": 15,
      "title": "Solar plants — AI inspection"
    },
    "uz": {
      "pages": 15,
      "title": "Quyosh stansiyalari — AI-inspeksiya"
    },
    "ch": {
      "pages": 14,
      "title": "太阳能电站 — AI巡检"
    }
  },
  "power": {
    "ru": {
      "pages": 15,
      "title": "От инспекции к управлению ЛЭП — UNB Group",
      "page": "/decks/power/"
    },
    "en": {
      "pages": 15,
      "title": "From inspection to power line management — UNB Group",
      "page": "/en/decks/power/"
    },
    "uz": {
      "pages": 15,
      "title": "Inspeksiyadan elektr uzatish liniyalarini boshqarishga — UNB Group",
      "page": "/uz/decks/power/"
    },
    "ch": {
      "pages": 15,
      "title": "从巡检到输电线路管理 — UNB Group",
      "page": "/zh/decks/power/"
    }
  },
  "city": {
    "ru": {
      "pages": 10,
      "title": "Интеллектуальная платформа Smart City — UNB Group",
      "page": "/decks/city/"
    },
    "en": {
      "pages": 10,
      "title": "Smart City monitoring and management platform — UNB Group",
      "page": "/en/decks/city/"
    },
    "uz": {
      "pages": 10,
      "title": "Smart City monitoring va boshqaruv platformasi — UNB Group",
      "page": "/uz/decks/city/"
    },
    "ch": {
      "pages": 10,
      "title": "智慧城市监测与管理平台 — UNB Group",
      "page": "/zh/decks/city/"
    }
  },
  "roads": {
    "ru": {
      "pages": 16,
      "title": "Интеллектуальные решения для инспекции дорог — UNB Group",
      "page": "/decks/roads/"
    },
    "en": {
      "pages": 16,
      "title": "Intelligent road inspection solutions — UNB Group",
      "page": "/en/decks/roads/"
    },
    "uz": {
      "pages": 16,
      "title": "Yo'llarni inspeksiya qilishning intellektual yechimlari — UNB Group",
      "page": "/uz/decks/roads/"
    },
    "ch": {
      "pages": 16,
      "title": "道路巡检智能解决方案 — UNB Group",
      "page": "/zh/decks/roads/"
    }
  },
  "construction": {
    "ru": {
      "pages": 10,
      "title": "Стройка — цифровой контроль строительства"
    },
    "en": {
      "pages": 10,
      "title": "Construction — digital site control"
    },
    "uz": {
      "pages": 10,
      "title": "Qurilish — raqamli nazorat"
    },
    "ch": {
      "pages": 10,
      "title": "建筑工地 — 数字化施工管控"
    }
  },
  "mapping": {
    "ru": {
      "pages": 7,
      "title": "Современная картография: цифровой двойник объекта — UNB Group",
      "page": "/decks/mapping/"
    },
    "en": {
      "pages": 7,
      "title": "Modern mapping: a digital twin of your site — UNB Group",
      "page": "/en/decks/mapping/"
    },
    "uz": {
      "pages": 7,
      "title": "Zamonaviy kartografiya: obyektingizning raqamli egizagi — UNB Group",
      "page": "/uz/decks/mapping/"
    },
    "ch": {
      "pages": 7,
      "title": "现代测绘：您的项目数字孪生 — UNB Group",
      "page": "/zh/decks/mapping/"
    }
  },
  "farming": {
    "ru": {
      "pages": 7,
      "title": "Smart Farming: цифровой двойник агробизнеса — UNB Group",
      "page": "/decks/farming/"
    },
    "en": {
      "pages": 7,
      "title": "Smart Farming: a digital twin of your agribusiness — UNB Group",
      "page": "/en/decks/farming/"
    },
    "uz": {
      "pages": 7,
      "title": "Smart Farming: agrobiznesingizning raqamli egizagi — UNB Group",
      "page": "/uz/decks/farming/"
    },
    "ch": {
      "pages": 7,
      "title": "智慧农业：您的农业数字孪生 — UNB Group",
      "page": "/zh/decks/farming/"
    }
  },
  "hardware": {
    "ru": {
      "pages": 7,
      "title": "Комплексные поставки БПЛА и энергооборудования — UNB Group",
      "page": "/decks/hardware/"
    },
    "en": {
      "pages": 7,
      "title": "Turnkey supply of industrial drones and power equipment — UNB Group",
      "page": "/en/decks/hardware/"
    },
    "uz": {
      "pages": 7,
      "title": "Sanoat BPLA va energiya uskunalarini kompleks yetkazib berish — UNB Group",
      "page": "/uz/decks/hardware/"
    },
    "ch": {
      "pages": 7,
      "title": "工业无人机与能源设备一体化供应 — UNB Group",
      "page": "/zh/decks/hardware/"
    }
  }
};
