/* Generated by tools/build-decks.mjs — do not edit by hand. */
const DECKS_INDEX = {
  "group": {
    "ru": {
      "pages": 19,
      "title": "UNB Group — платформа мониторинга инфраструктуры"
    },
    "en": {
      "pages": 19,
      "title": "UNB Group — infrastructure monitoring platform"
    },
    "uz": {
      "pages": 19,
      "title": "UNB Group — infratuzilma monitoringi platformasi"
    }
  },
  "solar": {
    "ru": {
      "pages": 15,
      "title": "Солнечные станции — AI-инспекция"
    },
    "en": {
      "pages": 15,
      "title": "Solar plants — AI inspection"
    },
    "uz": {
      "pages": 15,
      "title": "Quyosh stansiyalari — AI-inspeksiya"
    },
    "ch": {
      "pages": 14,
      "title": "太阳能电站 — AI巡检"
    }
  },
  "power": {
    "ru": {
      "pages": 16,
      "title": "ЛЭП — интеллектуальная инспекция"
    },
    "en": {
      "pages": 16,
      "title": "Power lines — intelligent inspection"
    },
    "uz": {
      "pages": 16,
      "title": "EUT — intellektual inspeksiya"
    },
    "ch": {
      "pages": 15,
      "title": "输电线路 — 智能巡检"
    }
  },
  "city": {
    "ru": {
      "pages": 11,
      "title": "Смарт-сити — цифровой двойник города"
    },
    "en": {
      "pages": 11,
      "title": "Smart city — digital twin"
    },
    "uz": {
      "pages": 11,
      "title": "Aqlli shahar — raqamli egizak"
    },
    "ch": {
      "pages": 11,
      "title": "智慧城市 — 城市数字孪生"
    }
  },
  "roads": {
    "ru": {
      "pages": 17,
      "title": "Дороги — AI-аналитика дорожной сети"
    },
    "en": {
      "pages": 15,
      "title": "Roads — AI road-network analytics"
    },
    "uz": {
      "pages": 15,
      "title": "Yo'llar — yo'l tarmog'ining AI-tahlili"
    },
    "ch": {
      "pages": 15,
      "title": "道路 — 道路网AI分析"
    }
  },
  "construction": {
    "ru": {
      "pages": 10,
      "title": "Стройка — цифровой контроль строительства"
    },
    "en": {
      "pages": 10,
      "title": "Construction — digital site control"
    },
    "uz": {
      "pages": 10,
      "title": "Qurilish — raqamli nazorat"
    },
    "ch": {
      "pages": 10,
      "title": "建筑工地 — 数字化施工管控"
    }
  }
};
