/**
 * Собирает языковые копии главной: /en/, /uz/, /zh/.
 *
 * Зачем: переключатель языков на сайте работает в браузере, поэтому у всех
 * четырёх версий был один адрес «/». Поисковик видит по нему только русский
 * текст — по английским и узбекским запросам сайт просто не появляется.
 * Отдельный URL с готовым текстом решает это без сервера: GitHub Pages сам
 * отдаёт /en/ из /en/index.html.
 *
 * index.html — единственный источник правды. Копии генерируются, править их
 * руками нельзя: следующий прогон затрёт изменения.
 *
 * Usage:  node tools/build-pages.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'node-html-parser';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://' + fs.readFileSync(path.join(ROOT, 'CNAME'), 'utf8').trim();

// Внутренний код языка -> каталог на сайте. Русский остаётся в корне: у «/»
// уже есть входящие ссылки и позиции, а редиректы на GitHub Pages не сделать.
const DIRS = { ru: '', en: 'en', uz: 'uz', ch: 'zh' };
// Google понимает 'zh', а не внутренний код 'ch'.
const HREFLANG = { ru: 'ru', en: 'en', uz: 'uz', ch: 'zh' };

const LANGS = Object.keys(DIRS);

function loadDict() {
  const src = fs.readFileSync(path.join(ROOT, 'js', 'i18n.js'), 'utf8');
  const m = src.match(/const I18N\s*=\s*(\{[\s\S]*\});\s*$/);
  if (!m) throw new Error('Не разобрать js/i18n.js');
  return new Function('return ' + m[1])();
}

const urlFor = (lang) => ORIGIN + '/' + (DIRS[lang] ? DIRS[lang] + '/' : '');

/**
 * Пути в index.html относительные (assets/…, css/…, deck.html). Из /en/ они
 * разрешились бы в /en/assets/… — переводим в корневые.
 */
function absolutizePaths(doc) {
  for (const attr of ['src', 'href']) {
    for (const el of doc.querySelectorAll(`[${attr}]`)) {
      const v = el.getAttribute(attr);
      if (!v) continue;
      // Внешние ссылки, якоря, tel:/mailto: и уже корневые пути не трогаем.
      if (/^([a-z]+:|\/\/|\/|#)/i.test(v)) continue;
      el.setAttribute(attr, '/' + v);
    }
  }
}

function setHeadLinks(doc, lang) {
  const head = doc.querySelector('head');
  for (const el of doc.querySelectorAll('link[rel="canonical"], link[rel="alternate"]')) {
    el.remove();
  }
  const links = [`<link rel="canonical" href="${urlFor(lang)}">`];
  for (const l of LANGS) {
    links.push(`<link rel="alternate" hreflang="${HREFLANG[l]}" href="${urlFor(l)}">`);
  }
  links.push(`<link rel="alternate" hreflang="x-default" href="${urlFor('ru')}">`);

  const icon = head.querySelector('link[rel="icon"]');
  const block = '\n' + links.join('\n') + '\n';
  if (icon) icon.insertAdjacentHTML('beforebegin', block);
  else head.insertAdjacentHTML('beforeend', block);
}

/** Подставляет переводы в узлы, размеченные data-i18n. */
function translate(doc, dict) {
  let n = 0;
  for (const el of doc.querySelectorAll('[data-i18n]')) {
    const value = dict[el.getAttribute('data-i18n')];
    if (value === undefined) continue;
    // data-i18n-html несёт разметку внутри строки (акцентные span в герое).
    if (el.hasAttribute('data-i18n-html')) el.set_content(value);
    else el.set_content(escapeHtml(value));
    n++;
  }
  return n;
}

const escapeHtml = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const escapeAttr = (s) => escapeHtml(s).replace(/"/g, '&quot;');

function buildPage(template, lang, dict) {
  const doc = parse(template, { comment: true });

  doc.querySelector('html').setAttribute('lang', HREFLANG[lang]);
  doc.querySelector('title').set_content(escapeHtml(dict['meta.title']));
  doc
    .querySelector('meta[name="description"]')
    .setAttribute('content', escapeAttr(dict['meta.description']));

  const translated = translate(doc, dict);

  // Активная вкладка переключателя проставляется здесь, а не в браузере:
  // без JS страница всё равно должна показывать свой язык выделенным.
  for (const el of doc.querySelectorAll('.lang-btn')) {
    const active = el.getAttribute('data-lang') === lang;
    el.classList.remove('is-active');
    if (active) el.classList.add('is-active');
  }

  absolutizePaths(doc);
  setHeadLinks(doc, lang);

  const banner =
    '<!-- Generated by tools/build-pages.mjs from index.html — do not edit by hand. -->\n';
  // Удаление старых <link> оставляет за собой пустые строки — подчищаем,
  // но только в <head>, чтобы не трогать форматирование разметки.
  const html = doc
    .toString()
    .replace(/<head>[\s\S]*?<\/head>/, (head) => head.replace(/\n{2,}/g, '\n'))
    .replace(/^(<!DOCTYPE html>\n)/i, `$1${banner}`);

  return { html, translated };
}

/**
 * index.html не генерируется — это шаблон, и переписывать его же выводом
 * парсера значит рисковать исходником ради нуля пользы. Но список hreflang
 * в нём написан руками, поэтому сверяем, что он не разошёлся с остальными.
 */
function checkTemplateHeadLinks(template) {
  const missing = [
    `<link rel="canonical" href="${urlFor('ru')}">`,
    ...LANGS.map((l) => `<link rel="alternate" hreflang="${HREFLANG[l]}" href="${urlFor(l)}">`),
    `<link rel="alternate" hreflang="x-default" href="${urlFor('ru')}">`,
  ].filter((tag) => !template.includes(tag));

  if (missing.length) {
    throw new Error(
      'В index.html не хватает ссылок в <head> — добавьте их вручную:\n  ' +
        missing.join('\n  ')
    );
  }
}

function main() {
  const I18N = loadDict();
  const template = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  checkTemplateHeadLinks(template);

  for (const lang of LANGS) {
    const dict = I18N[lang];
    if (!dict) throw new Error(`Нет словаря для «${lang}»`);
    for (const key of ['meta.title', 'meta.description']) {
      if (!dict[key]) throw new Error(`Нет ключа ${key} для «${lang}»`);
    }
    if (lang === 'ru') continue;

    const { html, translated } = buildPage(template, lang, dict);
    const dir = path.join(ROOT, DIRS[lang]);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'index.html'), html, 'utf8');
    console.log(`/${DIRS[lang]}/ — ${translated} переведённых узлов`);
  }
}

main();
